### ISSUE TITLE
some minor changes

### ISSUE THREAD

**Issue by plming** [ANU-CE/anubot-data-crawling#3]
# 작업 목록
- [x] 관계형 DB(MySQL) 관련 코드 제거
   - RDB가 아닌 Vector DB를 사용하기로 하였으므로, 사용되지 않는 코드 제거
- [x] 여러 collection에서 단일 collection으로 변경
   - 새 collection { name: "openai_ada_2", dimension: 1536, metric: cosine } 으로 migration
- [x] payload schema 설계 및 합의
   - created_datetime은 [ISO 8601](https://ko.wikipedia.org/wiki/ISO_8601)로 나타낸 UTC 시간으로 합니다.
```json
{
  "plain_text": "이 문장은 임베딩 벡터로 변환하기 전의 문장입니다",
  "created_datetime": "2023-08-25T13:51:07+00:00"
}
```
- [x] 임베딩 구현체 변경
   - jhgan/ko-sroberta-multitask에서 OpenAI/Embeddings API로 변경
   - 참조: https://platform.openai.com/docs/guides/embeddings
- [x] Github Actions 배포 Fail 해결

**Comment by AstralEUD** [comment]
TODO/ 학식정보
